// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Farsiman.Entities.Entities
{
    public partial class tbLotes
    {
        public int lote_Id { get; set; }
        public int prod_Id { get; set; }
        public DateTime? lote_FechaVencimiento { get; set; }
        public int? lote_Cantidad { get; set; }
        public int? lote_Precio { get; set; }

        public virtual tbProductos prod { get; set; }
    }
}