// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Farsiman.Entities.Entities
{
    public partial class tbSalidas
    {
        public int sali_Id { get; set; }
        public int? sucu_Id { get; set; }
        public DateTime? sali_Fecha { get; set; }
        [NotMapped]
        public string? sucu_Nombre { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        [NotMapped]
        public string? usua_Nombre { get; set; }
        [NotMapped]
        public string? sade_Total { get; set; }
        [NotMapped]
        public string? Respuesta { get; set; }
        public DateTime usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public int? sali_Estado { get; set; }
        [NotMapped]
        public string? Detalles { get; set; }


        public virtual tbSucursale sucu { get; set; }
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
    }
}