// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Farsiman.Entities.Entities
{
    public partial class tbSalidasDetalles
    {
        public int sade_Id { get; set; }
        public int? sali_Id { get; set; }
        [NotMapped]
        public string prod_PrecioReal { get; set; }
        [NotMapped]
        public string prod_Descripcion { get; set; }
        public int? prod_Id { get; set; }
        public int? sade_Cantidad { get; set; }
    }
}