// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Farsiman.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            tbPantallasusua_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasusua_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbProductosusua_UsuarioCreacionNavigation = new HashSet<tbProductos>();
            tbProductosusua_UsuarioModificacionNavigation = new HashSet<tbProductos>();
            tbRolesXPantallasusua_UsuarioCreacionNavigation = new HashSet<tbRolesXPantallas>();
            tbRolesXPantallasusua_UsuarioModificacionNavigation = new HashSet<tbRolesXPantallas>();
            tbRolesusua_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesusua_UsuarioModificacionNavigation = new HashSet<tbRoles>();
            tbSalidasusua_UsuarioCreacionNavigation = new HashSet<tbSalidas>();
            tbSalidasusua_UsuarioModificacionNavigation = new HashSet<tbSalidas>();
        }

        public int usua_Id { get; set; }
        public string usua_Nombre { get; set; }
        public string usua_Contrasenia { get; set; }
        public int empl_Id { get; set; }
        public int role_Id { get; set; }
        [NotMapped]
        public string role_Descripcion { get; set; }
        public bool usua_EsAdmin { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }

        public virtual ICollection<tbPantallas> tbPantallasusua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasusua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosusua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosusua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasusua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasusua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesusua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesusua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbSalidas> tbSalidasusua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbSalidas> tbSalidasusua_UsuarioModificacionNavigation { get; set; }
    }
}